# Practical_6: Numpy

In [103]:
import numpy as np

In [104]:
 
x=np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [106]:
A=np.zeros((3,3))
A.astype(int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

In [87]:
E = np.linspace(0, 5, 10,endpoint='false')
print(E)


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [ ]:
### Exercise 4:
Create a 5x5 identity matrix using NumPy.

In [86]:
identity_matrix = np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

In [37]:
matrix = np.random.rand(4, 4)
print(matrix)


[[0.49323925 0.41445757 0.30175037 0.13392206]
 [0.43488161 0.81491831 0.00967832 0.6686913 ]
 [0.9539635  0.84237314 0.76398778 0.0553132 ]
 [0.64179102 0.3721295  0.21546568 0.66522535]]


In [89]:
T=np.random.seed(0)
T

In [90]:
matrix = np.random.rand(4, 4)
print(matrix)


[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]


In [91]:
T=np.random.seed(10)
T

In [44]:

matrix = np.random.rand(4, 4)
print(matrix)


[[0.77132064 0.02075195 0.63364823 0.74880388]
 [0.49850701 0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607]]


In [ ]:
### Exercise 6:
Find the shape of a NumPy array.

In [54]:
W=np.arange(16)
print(W)
W=W.reshape(4,4)
print(W)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [57]:
E=np.arange(1,100,1)
E

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
### Exercise 8:
Find the data type of the elements in a NumPy array.

In [ ]:
### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [60]:
E=np.arange(2,101,2)
E

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

In [61]:
E=np.random.randint(10,50, (6,6))
E

array([[18, 46, 24, 23, 15, 23],
       [35, 23, 38, 32, 40, 40],
       [35, 22, 11, 41, 46, 37],
       [28, 39, 23, 32, 33, 40],
       [21, 38, 20, 34, 19, 25],
       [28, 26, 17, 34, 21, 27]])

In [ ]:
### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

In [105]:

arr = np.array([[1,2,3],[4,5,6]])

submatrix = arr[0:1, 0:2]

print(submatrix)


[[1 2]]


In [ ]:
### Exercise 12:
Calculate the sum of all elements in a NumPy array.

In [64]:

MA = np.array([1, 2, 3, 4, 5])
sum1 = np.sum(MA)

print("Sum of all elements:", sum1)
  

Sum of all elements: 15


In [ ]:
### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [80]:

Median=np.median(MA)
mean=np.mean(MA)
standard=np.std(MA)
print(standard)
print(Median)
print(mean)

1.4142135623730951
3.0
3.0


In [ ]:
### Exercise 14:
Find the maximum and minimum values in a NumPy array.

In [83]:
maximum=np.max(MA)
minimum=np.min(MA)
print(minimum)
print(maximum)

1
5


In [ ]:
### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

In [100]:
M2=np.arange(1,20,1)
print(M2)
maxx=np.where(M2==max(M2))
print(maxx)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(array([18], dtype=int64),)


In [103]:
np.argmax(M2)

18

In [ ]:
### Exercise 16:
Create a NumPy array and reverse its elements.

In [107]:
K=np.flip(M2)
K

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1])

In [ ]:
### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [114]:
M3=np.arange(9).reshape(3,3)
M4=np.arange(9).reshape(3,3)
prod=M3*M4
prod

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [ ]:
### Exercise 18:
Create a diagonal matrix from a given 1D array.

In [133]:
D1=np.arange(3)
D1=np.eye(2)
D1

array([[1., 0.],
       [0., 1.]])

In [ ]:
### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

In [134]:
X2=np.arange(4).reshape(2,2)
X3=np.arange(4).reshape(2,2)
P=X2*X3
P

array([[0, 1],
       [4, 9]])

In [ ]:
### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

In [135]:
D2 = np.array([[1, 2, 3], [4, 5, 6]])

FD = D2.flatten()

print(FD)


[1 2 3 4 5 6]


In [ ]:
### Exercise 21:
Stack two NumPy arrays vertically.

In [101]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
stacked_array = np.vstack((array1, array2))

print(stacked_array)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
### Exercise 22:
Stack two NumPy arrays horizontally.

In [100]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
stacked_array = np.hstack((array1, array2))

print(stacked_array)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
### Exercise 23:
Split a NumPy array into multiple sub-arrays.

In [99]:
A=np.array([1,2,3,4,5,6,7,8,9])
Split_A =np.split(A,3)
print(Split_A)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [ ]:
### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

In [98]:
random_array = np.random.rand(3, 4) 

# Round each element to two decimal places
rounded_array = np.round(random_array, 2)

print(rounded_array)


[[0.   0.51 0.81 0.61]
 [0.72 0.29 0.92 0.71]
 [0.54 0.14 0.37 0.67]]


In [ ]:
### Exercise 25:
Find the unique elements of a NumPy array.

In [8]:
Elements=np.array([1,2,2,4,4,4,3,3,5,5,6])
Unique_values=np.unique(Elements)
Unique_values

array([1, 2, 3, 4, 5, 6])

In [ ]:
### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

In [ ]:
### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

In [97]:
# Create a NumPy array
A = np.array([1, 2, 3, 4, 5, 6])
# Find the cumulative sum
cumulative_sum = np.cumsum(A)
print(cumulative_sum)

[ 1  3  6 10 15 21]


In [ ]:
### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

In [96]:
A1=np.array([1, 0, 2, 4, 0, 6, 0, 7])
A2=np.count_nonzero(A1)
print(A2) 

5


In [ ]:
### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

In [22]:
M1=np.random.randint(1,30,5)
print(M1)
M2=np.sort(M1)
print(M2)

[22  8 28 27  6]
[ 6  8 22 27 28]


In [ ]:
### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

In [112]:
# Create a 3x3 matrix
matrix = np.array([[1, 2, 3],[7, 8, 9]])

# Calculate the row-wise sum 
row_sum = np.sum(matrix, axis=1)

# Calculate the column-wise sum 
column_sum = np.sum(matrix, axis=0)

print("Matrix:")
print(matrix)
print("Row-wise sum:", row_sum)
print("Column-wise sum:", column_sum)


Matrix:
[[1 2 3]
 [7 8 9]]
Row-wise sum: [ 6 24]
Column-wise sum: [ 8 10 12]


In [ ]:
### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

In [111]:
random_array = np.random.rand(3, 4) * 100  
# Normalize the array
min_val = random_array.min()
max_val = random_array.max()
normalized_array = (random_array - min_val) / (max_val - min_val)

print("Random Array:",)
print(random_array)

print("Normalized Array:")
print(normalized_array)


Random Array:
[[80.52231968 52.16471524 90.86488808 31.9236089 ]
 [ 9.04593493 30.07000566 11.39843619 82.86813263]
 [ 4.68963194 62.62871483 54.75861559 81.92869957]]
Normalized Array:
[[0.87998216 0.55091317 1.         0.31603012]
 [0.05055167 0.29452043 0.0778507  0.90720358]
 [0.         0.67234013 0.58101346 0.89630215]]


In [ ]:
### Exercise 32:
Create two NumPy arrays and find the dot product.

In [32]:
matrix_1=np.array([1, 2, 3, 4, 5])
matrix_2=np.array([2, 1, 4, 3, 5])
prod=np.dot(matrix_1,matrix_2)
#prod=matrix_1 * matrix_2
print("The product is: ",prod)

The product is:  53


In [ ]:
### Exercise 33:
Find the trace of a square NumPy matrix

In [110]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the trace of the matrix
trace = np.trace(matrix)
print(matrix)
print("Trace of the matrix:", trace)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Trace of the matrix: 15


In [ ]:
### Exercise 34:
Create a 2D array and swap two rows.

In [92]:
# Create a 2D NumPy array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Specify the rows to swap
row1, row2 = 0, 1

# Swap the rows
array[[row1, row2]] = array[[row2, row1]]

print(" swapping array:")
print(array)


 swapping array:
[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [ ]:
### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

In [109]:
# Create a 1D NumPy array
d1 = np.array([1, 2, 3, 4, 5])

# Convert it into a column vector
column_vector = d1.reshape(-1, 1)

print("1D Array:")
print(d1)

print("Column Vector:")
print(column_vector)


1D Array:
[1 2 3 4 5]
Column Vector:
[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
### Exercise 36:
Find the determinant of a 3x3 matrix.

In [108]:


matrix = np.array([[1, 4, 3],
                   [1, 5, 4],
                   [9, 2, 6]])

# Calculate the determinant of the matrix
determinant = np.linalg.det(matrix)
det1=np.round(determinant)
print("Matrix:")
print(matrix)
print("Determinant of the matrix:", det1)


Matrix:
[[1 4 3]
 [1 5 4]
 [9 2 6]]
Determinant of the matrix: 13.0


In [ ]:
### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

In [49]:
R=np.array([[2, 4],[6, 8]])
e_values,e_vectors=np.linalg.eig(R)
print("The eigen values are:" )
print(e_values)
print("The eigen vectors are:" )
print(e_vectors)

The eigen values are:
[-0.74456265 10.74456265]
The eigen vectors are:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
### Exercise 38:
Solve a system of linear equations using NumPy.

In [51]:
A = np.array([[2, 3],
              [4, 5]])

# Constant terms vector
b = np.array([8, 18])

# Solve the system of equations
solution = np.linalg.solve(A, b)

print("Solution:")
print("x =", solution[0])
print("y =", solution[1])


Solution:
x = 7.0
y = -2.0


In [ ]:
### Exercise 39:
Add Gaussian noise to a NumPy array.

In [107]:

original_array = np.array([1, 2, 3, 4, 5])
mean = 0  # Mean of the Gaussian noise
std_dev = 0.5  # Standard deviation of the Gaussian noise

# Generate Gaussian noise
noise = np.random.normal(mean, std_dev, original_array.shape)

noisy_array = original_array + noise

print("Original Array:")
print(original_array)

print("Noisy Array:")
print(noisy_array)


Original Array:
[1 2 3 4 5]
Noisy Array:
[0.01113586 1.12831385 3.13303508 5.19248367 5.56184563]


In [ ]:
### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

In [55]:
G=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [10, 12, 14, 16],
            [9, 11, 13, 15]])
G1=np.diagonal(G)
print(G1)

[ 1  6 14 15]


In [ ]:
### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

In [56]:

random_values = np.random.uniform(0, 100, size=100)

# Clip the values to the range between 10 and 50
clipped_values = np.clip(random_values, 10, 50)

print("Random Values:")
print(random_values)

print("Clipped Values:")
print(clipped_values)


Random Values:
[86.17839913 15.42592496 24.98400927 55.5381985  17.61707591 20.029582
 17.1261362  60.85258314 13.91158519  6.94666762 31.74835123 24.0434417
  1.09592248 94.50009705 50.16608065 39.35463119 25.09743523  6.19379703
 16.6218934  40.79185753  8.53193389 33.23384152 81.71421694 50.80136907
 41.52202285 80.30940152 84.73756919 90.54334763 40.61866129 34.84396428
 78.12742647 94.87506944 61.3989911  45.00965632 74.23363476 61.02572076
 44.77884055 21.50566365 42.86283278  0.85938071 74.74241476 53.48899933
  5.76722152 25.16998075 43.93807029 63.90347155 77.17982319 38.71886959
  5.64343411 65.13377463 12.64501908 49.72443851 33.34054811 10.04119181
 31.10661414 87.84348233 60.2037806  34.07863593 41.51064521  5.07533639
 60.82224393 71.97743525 14.32372686 52.30884076 73.73133711 39.26268988
 29.4458578   3.70824133  7.54789298 99.2341877  66.5798375  74.31736745
  5.12506379 84.32854357 94.79239168 33.88207702 34.7346186  34.95763763
 57.53849663 26.95050743 58.91675013 78

In [ ]:
### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

In [58]:


# Create a 2D NumPy array with some negative values
array_2d = np.array([[1, -2, 3],
                     [7, -8, 9]])

print("Original Array:")
print(array_2d)

# Replace all negative values with zero
array_2d[array_2d < 0] = 0

print("Array after replacing negative values with zero:")
print(array_2d)

Original Array:
[[ 1 -2  3]
 [ 7 -8  9]]

Array after replacing negative values with zero:
[[1 0 3]
 [7 0 9]]


In [ ]:
### Exercise 43:
Find the inner and outer products of two NumPy arrays.

In [59]:


# Define two 1D NumPy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Calculate the inner product
inner_product = np.dot(a, b)

# Calculate the outer product
outer_product = np.outer(a, b)

print("Array a:", a)
print("Array b:", b)
print("\nInner Product:", inner_product)
print("\nOuter Product:\n", outer_product)


Array a: [1 2 3]
Array b: [4 5 6]

Inner Product: 32

Outer Product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

In [63]:


# Define the structured data type
dtype = np.dtype([('name', 'U10'),  # Unicode string of length 10
                  ('age', 'i4'),   # Integer (4 bytes)
                  ('height', 'f4') # Float (4 bytes)
                 ])

# Create a structured NumPy array
data = np.array([('Alice', 30, 5.5),
                 ('Bob', 25, 6.0),
                 ('Charlie', 35, 5.8)],
                dtype=dtype)

print("Structured NumPy Array:")
print(data)


Structured NumPy Array:
[('Alice', 30, 5.5) ('Bob', 25, 6. ) ('Charlie', 35, 5.8)]


In [ ]:
### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

In [69]:

matrix = np.random.randint(0, 10, size=(5, 5))

# Count the occurrences of each unique value
unique_values, counts = np.unique(matrix, return_counts=True)

# Display the results
print("Matrix:")
print(matrix)

print("Unique Values and their Counts:")
for value, count in zip(unique_values, counts):
    print(f"Value {value}: {count} occurrences")


Matrix:
[[1 1 9 6 3]
 [2 3 3 6 0]
 [6 1 0 8 3]
 [2 3 7 4 3]
 [3 5 5 7 8]]
Unique Values and their Counts:
Value 0: 2 occurrences
Value 1: 3 occurrences
Value 2: 2 occurrences
Value 3: 7 occurrences
Value 4: 1 occurrences
Value 5: 2 occurrences
Value 6: 3 occurrences
Value 7: 2 occurrences
Value 8: 2 occurrences
Value 9: 1 occurrences


In [ ]:
### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

In [68]:


array = np.random.rand(3, 3)

# Compute the mean of each row
row_means = np.mean(array, axis=1, keepdims=True)

# Subtract the mean from each row
result_array = array - row_means

print("Original Array:")
print(array)

print("Row Means:")
print(row_means)

print("Resulting Array after Subtracting Row Means:")
print(result_array)


Original Array:
[[0.94488785 0.95339312 0.70976889]
 [0.90642949 0.70457974 0.46763236]
 [0.60544079 0.37659404 0.28730425]]
Row Means:
[[0.86934995]
 [0.69288053]
 [0.42311303]]
Resulting Array after Subtracting Row Means:
[[ 0.0755379   0.08404317 -0.15958107]
 [ 0.21354896  0.01169921 -0.22524817]
 [ 0.18232777 -0.04651899 -0.13580878]]


In [ ]:
### Exercise 48:

In [ ]:
### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

In [70]:


array = np.random.randint(0, 100, size=(10,))  # Change size=(10,) for a 1D array of 10 integers

# Check if any values are greater than 50
any_greater_than_50 = np.any(array > 50)

print("Array:")
print(array)

print("values greater than 50:", any_greater_than_50)


Array:
[73 58 30 66 49 28 66 45 82 29]
values greater than 50: True


In [ ]:
### Exercise 49:

In [ ]:
Calculate the moving average of a 1D NumPy array.

In [71]:

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Define the window size
window_size = 3

# Calculate the moving average using convolution
weights = np.ones(window_size) / window_size
moving_average = np.convolve(data, weights, mode='valid')

print("Original Array:")
print(data)

print("Moving Average (window size = {}):".format(window_size))
print(moving_average)


Original Array:
[ 1  2  3  4  5  6  7  8  9 10]

Moving Average (window size = 3):
[2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

In [72]:


# Create two 1D NumPy arrays
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])

# Calculate the Pearson correlation coefficient
correlation_matrix = np.corrcoef(x, y)
pearson_coefficient = correlation_matrix[0, 1]  # Get the correlation coefficient

print("Array x:", x)
print("Array y:", y)
print("Correlation Coefficient:", pearson_coefficient)

Array x: [1 2 3 4 5]
Array y: [5 4 3 2 1]

Pearson Correlation Coefficient: -0.9999999999999999


In [ ]:
### Exercise 51:
Convert a NumPy array of radians to degrees.

In [73]:

radians = np.array([0, np.pi/4, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi])

# Convert radians to degrees
degrees = np.degrees(radians)

print("Radians:")
print(radians)

print("Degrees:")
print(degrees)


Radians:
[0.         0.78539816 1.57079633 3.14159265 4.71238898 6.28318531]

Degrees:
[  0.  45.  90. 180. 270. 360.]


In [ ]:
### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

In [74]:


array = np.random.rand(10)

# Compute the variance
variance = np.var(array)

# Compute the standard deviation
standard_deviation = np.std(array)

print("Random Array:")
print(array)

print("Variance:", variance)
print("Standard Deviation:", standard_deviation)


Random Array:
[0.97450962 0.10806674 0.9309195  0.27345403 0.57420523 0.0141883
 0.33892168 0.62993501 0.28812302 0.22977558]

Variance: 0.09773557906835255
Standard Deviation: 0.31262690074328625


In [ ]:
### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

In [75]:

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Find the indices of the maximum values along each axis
max_indices_axis0 = np.argmax(array, axis=0)  #  along columns
max_indices_axis1 = np.argmax(array, axis=1)  #  along rows

print("Array:")
print(array)

print("Indices of Maximum Values along Axis 0 (columns):")
print(max_indices_axis0)

print("Indices of Maximum Values along Axis 1 (rows):")
print(max_indices_axis1)


Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Indices of Maximum Values along Axis 0 (columns):
[2 2 2]

Indices of Maximum Values along Axis 1 (rows):
[2 2 2]


In [ ]:
### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

In [77]:


matrix = np.array([[4, 2],
                   [3, 1]])

# Compute the inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)

print("Original Matrix:")
print(matrix)

print("Inverse Matrix:")
print(inverse_matrix)

# Verify the result by multiplying the original matrix by its inverse
identity_matrix = np.dot(matrix, inverse_matrix)
print("Product of Original and Inverse:")
print(identity_matrix)


Original Matrix:
[[4 2]
 [3 1]]

Inverse Matrix:
[[-0.5  1. ]
 [ 1.5 -2. ]]
Product of Original and Inverse:
[[1. 0.]
 [0. 1.]]


In [ ]:
### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

In [79]:

array = np.random.rand(10)  # Random values between 0 and 1

# Calculate the mean and standard deviation
mean = np.mean(array)
std_dev = np.std(array)

# Standardize the array
standardized_array = (array - mean) / std_dev

print("Original Array:")
print(array)

print("Mean:", mean)
print("Standard Deviation:", std_dev)

print("Standardized Array:")
print(standardized_array)

# Check the mean and variance of the standardized array
print("Mean of Standardized Array:", np.mean(standardized_array))
print("Variance of Standardized Array:", np.var(standardized_array))


Original Array:
[0.80821606 0.09919273 0.66645566 0.8448062  0.61375994 0.72964201
 0.6347442  0.03925307 0.66146407 0.16816254]
Mean: 0.526569648040838
Standard Deviation: 0.2876612957658631
Standardized Array:
[ 0.97909041 -1.4856949   0.48628722  1.10628908  0.30310055  0.7059426
  0.37604835 -1.69406378  0.46893489 -1.24593441]
Mean of Standardized Array: 0.0
Variance of Standardized Array: 0.9999999999999998


In [ ]:
### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

In [80]:

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# Perform element-wise addition
addition_result = array1 + array2

# Perform element-wise subtraction
subtraction_result = array1 - array2
print(array1)

print(array2)

print("Element-wise Addition:")
print(addition_result)

print("Element-wise Subtraction:")
print(subtraction_result)


[1 2 3 4 5]
[5 4 3 2 1]
Element-wise Addition:
[6 6 6 6 6]
Element-wise Subtraction:
[-4 -2  0  2  4]


In [ ]:
### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

In [81]:


array = np.random.rand(10)  # Array of 10 random values between 0 and 1

# Find the index of the maximum element
max_index = np.argmax(array)

print("Random Array:")
print(array)

print("Index of Maximum Element:", max_index)

print("Maximum Element:", array[max_index])


Random Array:
[0.19115613 0.57869896 0.12959348 0.85929784 0.61859079 0.92697318
 0.23125619 0.14660863 0.01350676 0.38690224]

Index of Maximum Element: 5
Maximum Element: 0.9269731775253222


In [ ]:
### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

In [82]:

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Rotate the array by 90 degrees counter-clockwise
rotated_array = np.rot90(array)

print("Original Array:")
print(array)

print("Rotated Array:")
print(rotated_array)


Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rotated Array:
[[3 6 9]
 [2 5 8]
 [1 4 7]]


In [ ]:
### Exercise 59:
Compute the Frobenius norm of a matrix.

In [83]:


matrixx = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Compute the Frobenius norm
frobenius_norm = np.linalg.norm(matrixx, 'fro')

print("Matrix:")
print(matrixx)

print("Frobenius Norm:", frobenius_norm)


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Frobenius Norm: 16.881943016134134


In [ ]:
### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

In [84]:

D3 = np.array([[[ 1,  2,  3,  4],
                       [ 5,  6,  7,  8],
                       [ 9, 10, 11, 12]],

                      [[13, 14, 15, 16],
                       [17, 18, 19, 20],
                       [21, 22, 23, 24]]])

print(D3)

subarray = D3[:, :2, :2]  # Taking all layers, first 2 rows, and first 2 columns

print("Sliced Subarray:")
print(subarray)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Sliced Subarray:
[[[ 1  2]
  [ 5  6]]

 [[13 14]
  [17 18]]]
